### ISSUE TITLE
Plot multiple attributes in same plot

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/tango-webapp#106]
Maybe this is a feature request for the more distant future: Sometimes it is very helpful to plot multiple attributes in the same window or to be able to see them at once (like measured force in x/y/z).

**Comment by Ingvord** [comment]
Well, that is actually easy: replace status message (big white rectangle) with plot in monitor view; instead of opening a new tab (when plot icon is clicked) add a new trace to the plot.

**Comment by feinfinger** [comment]
Hm, could you show me at some point, I don't see how to do it...

Cheers,
Fabian

----- Original Message -----

**Comment by Ingvord** [comment]
I mean it is not yet implemented - it is easy to implement this :) 03.04.2018, 12:43, "Fabian Wilde" <notifications@github.com>:Hm, could you show me at some point, I don't see how to do it...Cheers,Fabian----- Original Message -----> From: "Ingvord" <notifications@github.com>> To: "tango-controls/tango-webapp" <tango-webapp@noreply.github.com>> Cc: "Fabian Wilde" <fabian.wilde@hzg.de>, "Author" <author@noreply.github.com>> Sent: Thursday, 29 March, 2018 16:47:24> Subject: Re: [tango-controls/tango-webapp] Plot multiple attributes in same plot (#106)> Well, that is actually easy: replace status message (big white rectangle) with> plot in monitor view; instead of opening a new tab (when plot icon is clicked)> add a new trace to the plot.>>>> --> You are receiving this because you authored the thread.> Reply to this email directly or view it on GitHub:> https://github.com/tango-controls/tango-webapp/issues/106#issuecomment-377259271—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.   -- Ingvord

**Comment by feinfinger** [comment]
Ah, ok.

BTW: Do you prefer if I come with my ideas directly to you or is it better to post an issue on github?

Cheers,
Fabian

----- Original Message -----

**Comment by Ingvord** [comment]
GitHub issues must be! And we also sometimes have to discuss them. Both are totally OK, so keep going :) 03.04.2018, 14:25, "Fabian Wilde" <notifications@github.com>:Ah, ok.BTW: Do you prefer if I come with my ideas directly to you or is it better to post an issue on github?Cheers,Fabian----- Original Message -----> From: "Ingvord" <notifications@github.com>> To: "tango-controls/tango-webapp" <tango-webapp@noreply.github.com>> Cc: "Fabian Wilde" <fabian.wilde@hzg.de>, "Author" <author@noreply.github.com>> Sent: Tuesday, 3 April, 2018 12:13:13> Subject: Re: [tango-controls/tango-webapp] Plot multiple attributes in same plot (#106)> I mean it is not yet implemented - it is easy to implement this :) 03.04.2018,> 12:43, "Fabian Wilde" <notifications@github.com>:Hm, could you show me at some> point, I don't see how to do it...Cheers,Fabian----- Original Message ----->> From: "Ingvord" <notifications@github.com>> To: "tango-controls/tango-webapp"> <tango-webapp@noreply.github.com>> Cc: "Fabian Wilde" <fabian.wilde@hzg.de>,> "Author" <author@noreply.github.com>> Sent: Thursday, 29 March, 2018 16:47:24>> Subject: Re: [tango-controls/tango-webapp] Plot multiple attributes in same> plot (#106)> Well, that is actually easy: replace status message (big white> rectangle) with> plot in monitor view; instead of opening a new tab (when plot> icon is clicked)> add a new trace to the plot.>>>> --> You are receiving this> because you authored the thread.> Reply to this email directly or view it on> GitHub:>> https://github.com/tango-controls/tango-webapp/issues/106#issuecomment-377259271—You> are receiving this because you commented.Reply to this email directly, view it> on GitHub, or mute the thread.   -- Ingvord>> --> You are receiving this because you authored the thread.> Reply to this email directly or view it on GitHub:> https://github.com/tango-controls/tango-webapp/issues/106#issuecomment-378199916—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.   -- Ingvord
